# EFS를 사용하는 StorageClass (AWS EFS CSI 드라이버 사용)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-csi-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap  # EFS Access Point 자동 생성
  fileSystemId: fs-0532833a79c88f8ca  # 기존 EFS 파일 시스템 ID를 사용
  directoryPerms: "700"  # 기본 디렉토리 권한 설정
volumeBindingMode: Immediate
---
# EFS를 사용하는 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-csi-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-csi-sc
  resources:
    requests:
      storage: 5Gi
---
# EFS를 사용하는 파드 구성
apiVersion: v1
kind: Pod
metadata:
  name: efs-csi-pod
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: efs-storage
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-csi-pvc
