apiVersion: karpenter.k8s.aws/v1  # Karpenter의 EC2NodeClass API 버전
kind: EC2NodeClass               # EC2 인스턴스의 속성을 정의하는 EC2NodeClass 리소스
metadata:
  name: default                  # EC2NodeClass의 이름을 "default"로 설정
spec:
  amiFamily: AL2023              # Amazon Linux 2023 기반 AMI 사용
  role: ${node_iam_role_name}    # 노드에 할당할 IAM 역할 (템플릿 변수를 사용하여 정의)

  amiSelectorTerms:              # 사용할 AMI의 ID를 명시
    - id: ${ami_id}              # 템플릿에서 전달받은 AMI ID

  subnetSelectorTerms:           # Karpenter가 노드를 배치할 서브넷을 선택
    - tags:
        karpenter.sh/discovery: ${cluster_name}  # 서브넷을 선택할 때 해당 클러스터 이름으로 태그된 서브넷 선택
  securityGroupSelectorTerms:    # Karpenter가 노드를 생성할 때 사용할 보안 그룹 선택
    - tags:
        karpenter.sh/discovery: ${cluster_name}  # 클러스터 이름으로 태그된 보안 그룹 선택
  tags:
    karpenter.sh/discovery: ${cluster_name}      # 생성된 리소스(노드)에 클러스터 이름 태그 추가
